数据库系统原理/课程设计/peanutzhen/src/app/blueprint.py
from flask import (
    Blueprint,
    flash,
    redirect,
    url_for,
    render_template,
    request,
    send_file
)
from flask_login import (
    login_required,
    login_user,
    logout_user,
    current_user
)
from datetime import datetime
from .forms import (
    LoginForm,
    RegisterForm,
    JournalForm
)
from .models import (
    db,
    User,
    Journal,
    Email,
    Editor,
    Organizer,
    writing,
    management
)
# 创建名为 main 的蓝本
main = Blueprint('main', __name__)

### 开始定义路由

#################### 认证部分 ####################
@main.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    # POST
    if form.validate_on_submit():
        # 检查邮箱
        user = User.query.filter_by(email=form.email.data).first()
        # 检查密码
        if user is not None and user.verify_password(form.passwd.data):
            # 登录成功
            login_user(user)
            return redirect(url_for('main.index'))
        else:
            # 登录失败
            flash('无效的用户名或密码！', 'danger')
            return redirect(url_for('main.login'))
    # GET
    logout_user()   # 先登出用户，无论如何
    return render_template('login.html', form=form)

@main.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    # POST
    if form.validate_on_submit():
        # 构造新 User 对象
        new_user = User(
            name=form.username.data,
            em=form.email.data,
            pw=form.passwd.data,
            t=False
        )
        # 插入 users 表中
        db.session.add(new_user)
        db.session.commit()
        flash('注册成功！您可以登录啦！', 'success')
        return redirect(url_for('main.login'))
    # GET
    return render_template('register.html',form=form)
####################  分割线  ####################

#################### 主体部分 ####################

# 主界面
@main.route('/index')
@login_required
def index():
    # 获取数据库所有 journal 数据
    journals = Journal.query.all()
    username = current_user.username
    flash('目前期刊数: {}'.format(len(journals)), 'info')
    return render_template('index.html', journals=journals, username=username)

# 搜索功能路由
@main.route('/search', methods=['POST'])
@login_required
def search():
    # 获取 POST 数据
    option = request.form.get('option', None)
    found = request.form.get('search', '')
    # 检查输入栏是否为空
    if found is '':
        flash('输入栏为空!','info')
        return redirect(url_for('main.index'))
    else:
        start = datetime.now()  # 记录开始时间点
        # 根据 Option 查找与 found 模糊匹配的数据库
        if option == 'cn_name':
            found = Journal.cn_name.like('%{}%'.format(found))
            results = Journal.query.filter(found).all()
        elif option == 'issn':
            found = Journal.issn.like('{}%'.format(found))
            results = Journal.query.filter(found).all()
        elif option == 'cn':
            found = Journal.cn.like('{}%'.format(found))
            results = Journal.query.filter(found).all()
    end = datetime.now()  # 记录结束时间点
    msg = '查询用时: %.3fms' % ((end-start).total_seconds()*1000,)
    flash(msg,'success')
    # 渲染结果
    return render_template('sear_result.html', results=results)

# 增添期刊路由
@main.route('/insert', methods=['GET','POST'])
@login_required
def insert():
    journal_form = JournalForm()
    # 检查当前用户是否有权限
    if current_user.type == False:
        flash('此操作无权限对于当前用户。', 'danger')
        return redirect(url_for('main.index'))
    if journal_form.insert_submit.data and journal_form.validate():
        # 检查 issn/cn 是否重复
        sanity_check = []
        sanity_check.append(Journal.query.filter_by(issn=journal_form.issn.data).first())
        sanity_check.append(Journal.query.filter_by(cn=journal_form.cn.data).first())
        if sanity_check[0] is not None or sanity_check[1] is not None:
            flash('ISSN 或 CN 已存在数据库中！请仔细检查。', 'danger')
            return redirect(url_for('main.insert'))
        
        # 替换 '' 为 None
        if journal_form.tel.data == '':
            journal_form.tel.data = None
        if journal_form.fax.data == '':
            journal_form.fax.data = None 
        # 新建一个 Journal 对象
        insert_item = Journal(
            issn=journal_form.issn.data,
            cn=journal_form.cn.data,
            cn_name=journal_form.cn_name.data,
            en_name=journal_form.en_name.data,
            year=journal_form.public_year.data,
            cycle=journal_form.public_cycle.data,
            addr=journal_form.address.data,
            zipcode=journal_form.zipcode.data,
            tel=journal_form.tel.data,
            fax=journal_form.fax.data
        )
        # 解析 Emails/Editors/Organs 字段
        # 它们都是靠'/'来分割
        emails = journal_form.emails.data.split('/')
        editors = journal_form.editors.data.split('/')
        organs = journal_form.organizers.data.split('/')
        # 将这些信息与插入项关联
        for loop_item in emails:
            if loop_item == '': # 跳过空项
                continue
            if Email.query.filter_by(email=loop_item).first() is None:
                db.session.add(Email(loop_item, insert_item))
            else:
                flash('此邮箱已经存在，请仔细检查！', 'danger')
                return redirect(url_for('main.insert'))

        for loop_item in editors:
            if loop_item == '': # 跳过空项
                continue
            tmp = Editor.query.filter_by(name=loop_item).first()
            if tmp is None:     # 如果此前没出现过这个主编
                insert_item.editors.append(Editor(loop_item))
            else:
                tmp.journals.append(insert_item)

        for loop_item in organs:
            if loop_item == '': # 跳过空项
                continue
            tmp = Organizer.query.filter_by(name=loop_item).first()
            if tmp is None:     # 如果此前没出现过这个主办方
                insert_item.organizers.append(Organizer(loop_item))
            else:
                tmp.journals.append(insert_item)

        # 提交
        db.session.add(insert_item)
        db.session.commit()
        # 返回总览 并给出插入成功提示
        flash('期刊数据添加成功！', 'success')
        return redirect(url_for('main.index'))
    else:
        flash('1. *为必填项', 'info')
        flash('2. 电子邮箱/主编/主办单位多个时请用 / 隔开','info')
        return render_template('jour_form.html', form=journal_form)


# 删除期刊路由
@main.route('/delete/<issn>')
@login_required
def delete(issn):
    # 检查当前用户是否有权限
    if current_user.type == False:
        flash('此操作无权限对于当前用户。', 'danger')
        return redirect(url_for('main.index'))
    journal = Journal.query.filter_by(issn=issn).first()
    # 先删除所有依赖: Email/主编/主办单位
    for tmp in journal.emails:
        db.session.delete(tmp)
    for tmp in journal.editors:
        journal.editors.remove(tmp)
    for tmp in journal.organizers:
        journal.organizers.remove(tmp)
    # 先提交
    db.session.commit()
    # 再删掉他自己
    db.session.delete(journal)
    db.session.commit()
    flash('删除期刊 {} 成功！'.format(issn), 'success')
    return redirect(url_for('main.index'))

# 修改期刊路由
@main.route('/update/<issn>', methods=['GET','POST'])
@login_required
def update(issn):
    update_form = JournalForm()
    # 检查当前用户是否有权限
    if current_user.type == False:
        flash('此操作无权限对于当前用户。', 'danger')
        return redirect(url_for('main.index'))
    journal = Journal.query.filter_by(issn=issn).first()
    # POST 
    if update_form.insert_submit.data and update_form.validate():
        start = datetime.now()
        # 检查 issn/cn 是否重复
        sanity_check = []
        sanity_check.append(Journal.query.filter_by(issn=update_form.issn.data).first())
        sanity_check.append(Journal.query.filter_by(cn=update_form.cn.data).first())
        if sanity_check[0] is not None:
            if sanity_check[0].issn != journal.issn:
                flash('ISSN: {} 已存在数据库中！请仔细检查。'.format(journal.issn), 'danger')
                return redirect(url_for('main.insert'))
        if sanity_check[1] is not None:
            if sanity_check[1].cn != journal.cn:
                flash('CN: {} 已存在数据库中！请仔细检查。'.format(journal.cn), 'danger')
                return redirect(url_for('main.insert'))
        # 替换 '' 为 None
        if update_form.tel.data == '':
            update_form.tel.data = None
        if update_form.fax.data == '':
            update_form.fax.data = None 
        # 先删除之前的信息
        for tmp in journal.emails:
            db.session.delete(tmp)
        for tmp in journal.editors:
            journal.editors.remove(tmp)
        for tmp in journal.organizers:
            journal.organizers.remove(tmp)
        # 先提交删除 否则后面外键不统一
        db.session.commit()
        # 基本字段的修改
        journal.cn_name = update_form.cn_name.data
        journal.en_name = update_form.en_name.data
        journal.issn = update_form.issn.data
        journal.cn = update_form.cn.data
        journal.address = update_form.address.data
        journal.tel = update_form.tel.data
        journal.fax = update_form.fax.data
        journal.public_year = update_form.public_year.data
        journal.public_cycle = update_form.public_cycle.data
        journal.zipcode = update_form.zipcode.data
        # 一对多 多对多关系修改
        emails = update_form.emails.data.split('/')
        editors = update_form.editors.data.split('/')
        organs = update_form.organizers.data.split('/')
        
        for loop_item in emails:
            if loop_item == '': # 跳过空项
                continue
            if Email.query.filter_by(email=loop_item).first() is None:
                db.session.add(Email(loop_item, journal))
            else:
                flash('此邮箱已经存在，请仔细检查！', 'danger')
                return redirect(url_for('main.insert'))

        for loop_item in editors:
            if loop_item == '': # 跳过空项
                continue
            tmp = Editor.query.filter_by(name=loop_item).first()
            if tmp is None:     # 如果此前没出现过这个主编
                journal.editors.append(Editor(loop_item))
            else:
                tmp.journals.append(journal)

        for loop_item in organs:
            if loop_item == '': # 跳过空项
                continue

数据库系统原理/课程设计/peanutzhen/src/app/templates/about.html
{% extends 'main_base.html' %}

{% block title %}
    关于作者
{% endblock title %}

{% block page_content %}
    <div class="jumbotron">
        <h1>I am astzls.</h1>
        <p>
            暨南大学大三学生，欢迎与我交流。<br>
            邮箱: astzls213@163.com<br>
            Github: astzls213<br>
            微博: 钟海宁video<br>
            知乎: 钟海宁
        </p>
    </div>
{% endblock %}

数据库系统原理/课程设计/peanutzhen/src/app/templates/auth_base.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}登录 - 期刊管理系统{% endblock %}

{% block styles %}
{{ super() }}
<link href="../static/auth.css" rel="stylesheet">
{% endblock styles %}

{% block body %}
<div id="drag"></div>
{% block page_content %}
    
{% endblock %}
{% endblock %}

数据库系统原理/课程设计/peanutzhen/src/app/templates/index.html
{% extends 'main_base.html' %}

{% block panel_head %}
消息
{% endblock %}

{% block panel_body %}
{% for tag, msg in get_flashed_messages(with_categories=true) %}
<div class="alert alert-{{ tag }}" role="alert">
    {{ msg }}
</div>
{% endfor %}
<div class="jumbotron">
    <p>
        欢迎回来！{{ username }}。
    </p>
</div>
{% endblock panel_body %}

{% block table_head %}
<tr>
    <th class="col-md-1">编号</th>
    <th class="col-md-3">期刊名</th>
    <th class="col-md-3">英文名</th>
    <th class="col-md-3">主编</th>
    <th class="col-md-2">主办单位</th>
</tr>
{% endblock %}

{% block table_body %}
{% for journal in journals %}
    <tr>
        <td>{{ loop.index }}</td>
        <td><a href="{{ url_for('main.detail', issn=journal.issn) }}">{{ journal.cn_name }}</a></td>
        <td>{{ journal.en_name }}</td>
        <td>
        {% for editor in journal.editors %}
        {{ editor.name }} 
        {% endfor %}
        </td>
        <td>
        {% for organ in journal.organizers %}
        {{ organ.name }} 
        {% endfor %}
        </td>
    </tr>
{% endfor %}
{% endblock  %}

数据库系统原理/课程设计/peanutzhen/src/app/templates/jour_form.html
{% extends 'main_base.html' %}

{% block title %}
    新增期刊 - 期刊管理系统
{% endblock title %}

{% block panel_head %}
    注意事项
{% endblock panel_head %}

{% block panel_body %}
{% for tag, msg in get_flashed_messages(with_categories=true) %}
<div class="alert alert-{{ tag }}" role="alert">
    {{ msg }}
</div>
{% endfor %}
{% endblock panel_body %}

{% block custom_content %}
<form action="" method="post" class="form" role="form">
    {{ form.hidden_tag() }}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-4">
            {{ wtf.form_field(form.cn_name) }}
            {{ wtf.form_field(form.en_name) }}
        </div>
        <div class="col-md-2">
            {{ wtf.form_field(form.public_year) }}
            {{ wtf.form_field(form.public_cycle) }}
        </div>
        <div class="col-md-2">
            {{ wtf.form_field(form.tel) }}
            {{ wtf.form_field(form.fax) }}
        </div>
        <div class="col-md-2"></div>
    </div>

    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-4">
            {{ wtf.form_field(form.issn) }}
            {{ wtf.form_field(form.cn) }}
        </div>
        <div class="col-md-4">
            {{ wtf.form_field(form.zipcode) }}
        </div>
        <div class="col-md-2"></div>
    </div>
    
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            {{ wtf.form_field(form.organizers) }}
            {{ wtf.form_field(form.editors) }}
            {{ wtf.form_field(form.emails) }}
            {{ wtf.form_field(form.address) }}
        </div>
        <div class="col-md-2"></div>
    </div>

    <div class="row">
        <div class="col-md-5"></div>
        <div class="col-md-2">
            {{ wtf.form_field(form.insert_submit) }}
        </div>
        <div class="col-md-5"></div>
    </div>
</form>
{% endblock custom_content %}

数据库系统原理/课程设计/peanutzhen/src/app/templates/journal_detail.html
{% extends 'main_base.html' %}

{% block title %}
    详细信息 - 期刊管理系统
{% endblock title %}

{% block my_styles %}
<link rel="stylesheet" href="{{ url_for('static', filename='pop.css') }}">
{% endblock my_styles %}

{% block scripts %}
{{ super() }}
<script src="{{ url_for('static', filename='pop.js') }}"></script>
{% endblock scripts %}

{% block page_content %}
{# 这是弹窗部分 #}
<div id="popwin">
    <div class="panel panel-danger" >
        <div class="panel-heading">
            <h3 class="panel-title">警告</h3>
        </div>
        <div class="panel-body">
            <p>真的要删除吗？此操作无法撤销。</p>
            <a href="{{ url_for('main.delete', issn=journal.issn) }}" class="btn btn-danger">确定</a>
            <a id="cancel" href="#" class="btn btn-primary">取消</a>
        </div>
    </div>
</div>

{# 这是主体部分 #}
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <div class="row">
            <div class="jumbotron">
                <h1></h1>
                <p>
                    中文刊名: {{ journal.cn_name }}<br>
                    英文刊名: {{ journal.en_name }}<br>
                    ISSN: {{ journal.issn }}<br>
                    CN: {{ journal.cn }}<br>
                    主编: {% for editor in journal.editors %}{{ editor.name }} {% endfor %}<br>
                    主办单位: {% for organ in journal.organizers %}{{ organ.name }} {% endfor %}<br>
                    创刊时间: {{ journal.public_year }}<br>
                    出版周期(期/年): {{ journal.public_cycle }}<br>
                    地址: {{ journal.address }}<br>
                    邮编: {{ journal.zipcode }}<br>
                    电邮: {% for email in journal.emails %}{{ email.email }} {% endfor %}<br>
                    电话: {{ journal.tel }}<br>
                    传真: {{ journal.fax }}
                </p>
                <p>
                    <a href="{{ url_for('main.update', issn=journal.issn)}}" class="btn btn-primary">修改期刊信息</a>
                    <button class="btn" id="delete">
                        <span style="color:tomato;">删除该期刊</span>
                    </button>
                </p>
            </div>
        </div>
        
    </div>
    <div class="col-md-1"></div>
</div>
{% endblock page_content %}


            
            

数据库系统原理/课程设计/peanutzhen/src/app/templates/login.html
{% extends 'auth_base.html' %}

{% block page_content %}
    <div class="container">
        <form class="form-signin" method="POST">
            <h2 class="form-signin-heading">请登录</h2>
            
            {{ wtf.quick_form(form) }}
        </form>
        <p>
            新用户？
            <a href="{{ url_for('main.register') }}">
                点击这里注册！
            </a>
        </p>
        
        {% for tag, msg in get_flashed_messages(with_categories=true) %}
        <div class="alert alert-{{ tag }}" role="alert">
            {{ msg }}
        </div>
        {% endfor %}
    </div>
{% endblock %}

数据库系统原理/课程设计/peanutzhen/src/app/templates/main_base.html
{% extends 'bootstrap/base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
    期刊管理系统
{% endblock title %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="../static/main_frame.css">
{% block my_styles %}
    
{% endblock my_styles %}
{% endblock styles %}

{% block scripts %}
{{ super() }}
<script src=" {{ url_for('static', filename='renderer.js') }}"></script>
<script>window.jQuery = window.$ = module.exports</script>
{% endblock  %}

{# 这是导航栏 #}
{% block navbar %}
{# inverse 用于深色模式 fixed-top 用于固定#}
<nav id="top_nav" class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">   {# 流式布局 #}
        <div class="navbar-header">
            <a class="navbar-brand" href="#">期刊管理系统</a>
        </div>
        <ul id="top_nav_btn_list" class="nav navbar-nav navbar-right">
            <li><a href="{{ url_for('main.about') }}">关于作者</a></li>
        </ul>
        <form id="top_nav_form" class="navbar-form navbar-right" action="{{ url_for('main.search') }}" method="POST">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <select name="option" class="form-control">
                <option value="cn_name">中文刊名</option>
                <option value="issn">ISSN</option>
                <option value="cn">CN</option>
            </select>
            <input type="text" name="search" class="form-control" placeholder="Search...">
        </form>
    </div>
</nav>
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        {# 这是侧边栏 #}
        <div class="col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li class="active">
                    <a href="{{ url_for('main.index') }}">总览</a>
                </li>
                <li>
                    <a href="{{ url_for('main.insert') }}">增添新期刊</a>
                </li>
                <li>
                    <a id="gen_report" href="#">生成报表</a>
                </li>
                <li>
                    <a id="print_report" href="{{ url_for('main.print_report') }}">打印报表</a>
                </li>
            </ul>
        </div>
        {# 这是页面内容 #}
        <div class="col-md-10 col-md-offset-2 main">
        {% block page_content %}
        <div class="panel panel-default">
            <div class="panel-heading">
                {% block panel_head %}
                    
                {% endblock %}
            </div>
            <div class="panel-body">
                {% block panel_body %}
                    
                {% endblock %}
            </div>
            <table class="table table-striped">
                <thead>
                    {% block table_head %}
                        
                    {% endblock  %}
                </thead>
                <tbody>
                    {% block table_body %}
                        
                    {% endblock  %}
                </tbody>
            </table>
        </div>
        {% endblock page_content%}

        {% block custom_content %}
            
        {% endblock custom_content %}
        </div>
    </div>
</div>
{% endblock  %}

数据库系统原理/课程设计/peanutzhen/src/app/templates/print_report.html
{% extends 'main_base.html' %}
{% block title %}
   查看报表
{% endblock title %}

{% block page_content %}
<h3>
   报表预览
   <span class="label label-default">
      期刊报表
   </span>
</h3>
<div class="embed-responsive embed-responsive-4by3">
   <embed   type="application/pdf"
            src="{{ url_for('main.pdf') }}" 
            class="embed-responsive-item">
</div>

{% endblock page_content %}

数据库系统原理/课程设计/peanutzhen/src/app/templates/register.html
{% extends 'auth_base.html' %}

{% block title %}
    注册 - 期刊管理系统
{% endblock title %}

{% block page_content %}
    <div class="container">
        <form class="form-signin" method="POST">
            <h2 class="form-signin-heading">欢迎使用期刊管理系统</h2>
            {{ wtf.quick_form(form) }}
        </form>
        
        {% for msg in get_flashed_messages() %}
        <div class="alert alert-danger" role="alert">
            {{ msg }}
        </div>
        {% endfor %}
    </div>
{% endblock %}

数据库系统原理/课程设计/peanutzhen/src/app/templates/report.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>报表</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
        <link rel="stylesheet" href="{{ url_for('static', filename='report.css') }}">
    </head>
    <body>
        <!-- 报表标题 -->
        <div>
            <h1 style="text-align:center">期刊报表</h1>
        </div>
        <!-- 报表表格 -->
        <div class="wrapper">
            <div class="table">
                
                <div class="row header blue">
                    <div class="cell">
                        ISSN
                    </div>
                    <div class="cell">
                        中文刊名
                    </div>
                    <div class="cell">
                        主编
                    </div>
                    <div class="cell">
                        主办单位
                    </div>
                </div>
                
                {% for journal in journals %}
                <div class="row">
                    <div class="cell">
                        {{ journal.issn }}
                    </div>
                    <div class="cell">
                        {{ journal.cn_name }}
                    </div>
                    <div class="cell">
                        {% for editor in journal.editors %}
                        {{ editor.name }} 
                        {% endfor %}
                    </div>
                    <div class="cell">
                        {% for organ in journal.organizers %}
                        {{ organ.name }} 
                        {% endfor %}
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    </body>
</html>

数据库系统原理/课程设计/peanutzhen/src/app/templates/sear_result.html
{% extends 'main_base.html' %}

{% block title %}
    查询结果 - 期刊管理系统
{% endblock title %}

{% block panel_head %}
    查询结果
{% endblock panel_head %}

{% block panel_body %}
{% for tag, msg in get_flashed_messages(with_categories=true) %}
<div class="alert alert-{{ tag }}" role="alert">
    {{ msg }}
</div>
{% endfor %}
{% endblock panel_body %}

{% block table_head %}
<tr>
    <th class="col-md-1">编号</th>
    <th class="col-md-3">期刊名</th>
    <th class="col-md-3">英文名</th>
    <th class="col-md-3">主办方</th>
    <th class="col-md-2">主编</th>
</tr>
{% endblock table_head %}

{% block table_body %}
    {% for result in results %}
    <tr>
        <td>{{ loop.index }}</td>
        <td><a href="{{ url_for('main.detail', issn=result.issn) }}">{{ result.cn_name }}</a></td>
        <td>{{ result.en_name }}</td>
        <td>
        {% for editor in result.editors %}
        {{ editor.name }} 
        {% endfor %}
        </td>
        <td>
        {% for organ in result.organizers %}
        {{ organ.name }} 
        {% endfor %}
        </td>
    </tr>
    {% endfor %}
{% endblock table_body %}